# Generated by Django 6.0.3 on 2026-03-09 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainSectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restoran_name', models.CharField(max_length=20, unique=True)),
                ('restoran_icon', models.ImageField(upload_to='restoran_icons/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaIconModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media_name', models.CharField(max_length=20)),
                ('social_media_url', models.URLField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('main_section_model_relaion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_icons', to='qr_menu_app.mainsectionmodel')),
            ],
        ),
    ]
