# Generated by Django 6.0.3 on 2026-03-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_menu_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaiconmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
