# Generated by Django 6.0.3 on 2026-03-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_menu_app', '0002_socialmediaiconmodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsectionmodel',
            name='h1_sub_text',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainsectionmodel',
            name='h1_text',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainsectionmodel',
            name='restoran_reserve_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
