# Generated by Django 6.0.3 on 2026-03-09 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_menu_app', '0004_infosection_indexsliderphotomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosection',
            name='resetion_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='info_sections', to='qr_menu_app.mainsectionmodel'),
            preserve_default=False,
        ),
    ]
