# Generated by Django 6.0.3 on 2026-03-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_menu_app', '0005_infosection_resetion_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsectionmodel',
            name='about_us',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainsectionmodel',
            name='about_us_title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
