# Generated by Django 6.0.3 on 2026-03-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_menu_app', '0007_itemcategory_menuitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='price',
            new_name='original_price',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='menu_item_tags',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='allergen_information',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu_item_ingredients',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='price_save',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
