# Generated by Django 6.0.3 on 2026-03-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_menu_app', '0008_rename_price_menuitem_original_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ManyToManyField(related_name='menu_items', to='qr_menu_app.itemcategory'),
        ),
    ]
