# Generated by Django 6.0.3 on 2026-03-09 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_menu_app', '0009_remove_menuitem_category_menuitem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestoranGaleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galery_image', models.ImageField(upload_to='restoran_galery_photos/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('restoran_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restoran_galery_photos', to='qr_menu_app.mainsectionmodel')),
            ],
        ),
    ]
