# Generated by Django 6.0.3 on 2026-03-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_menu_app', '0010_restorangalerymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsectionmodel',
            name='footer_adress',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainsectionmodel',
            name='footer_open_time',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainsectionmodel',
            name='footer_phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainsectionmodel',
            name='footer_text',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
